# Item to use as a cube selecting tool.
# default: IRON_HOE
selecting-tool: IRON_HOE

experimental:
  # If enabled, the extension will track block changes made by players during the match instead of scanning
  # the entire arena after the match to locate the block changes. While much more efficient, this method
  # is unable to detect block changes caused by other plugins. If you're using such a plugin, avoid this option!
  # default: true
  track-block-changes: true

# Blocks to reset per tick.
blocks-per-tick: 100

# Allow breaking blocks in the reset zone that is not placed by a player in match.
# default: false
allow-arena-block-break: false

# Allow breaking blocks in the reset zone that is not placed by a player in match.
# default: auto
# available: [auto, fallback, v1_8_R3, v1_8_R3_paper, v1_12_R1, v1_14_R1, v1_15_R1, v1_16_R3, v1_17_R1, v1_18_R1, v1_18_R2]
block-reset-handler-version: auto

# Remove dropped items in the reset zone when the match ends.
# default: true
remove-dropped-items: true

# Remove entities in the reset zone when the match ends.
# default: [ENDER_CRYSTAL, MINECART_TNT]
remove-entities: [ENDER_CRYSTAL, MINECART_TNT]

# Prevent blocks in the reset zone from burning.
# default: true
prevent-block-burn: true

# Prevents blocks in the reset zone from melting. (snow, ice)
# default: true
prevent-block-melt: true

# Prevents blocks in the reset zone from exploding.
# default: false
prevent-block-explode: false

# Prevents fire in the reset zone from spreading.
# default: true
prevent-fire-spread: true

# Prevents tree leaves in the reset zone from decaying.
# default: true
prevent-leaf-decay: true